definitions:
  model.Metadata:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
  model.Product:
    properties:
      created_at:
        type: string
      id:
        type: string
      images:
        items:
          type: string
        type: array
      in_stock:
        type: boolean
      name:
        type: string
      qty:
        type: integer
      sku:
        type: string
      updated_at:
        type: string
    type: object
  model.SearchResponse:
    properties:
      metadata:
        $ref: '#/definitions/model.Metadata'
      products:
        items:
          $ref: '#/definitions/model.Product'
        type: array
    type: object
  model.UpdateRequest:
    properties:
      qty:
        type: integer
    type: object
info:
  contact:
    email: srodmendz@gmail.com
    name: Sebastian Rodriguez Mendez
paths:
  /health-check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - healthcheck
  /v1:
    get:
      consumes:
      - application/json
      description: Search products
      parameters:
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      - description: offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SearchResponse'
        "500":
          description: Internal Server Error
      tags:
      - search
    post:
      consumes:
      - application/json
      description: Create product
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Product'
        "500":
          description: Internal Server Error
      tags:
      - create
  /v1/{id}/:
    delete:
      consumes:
      - application/json
      description: Delete product
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      tags:
      - delete
    get:
      consumes:
      - application/json
      description: Get product by id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - get by id
    put:
      consumes:
      - application/json
      description: Update product
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateRequest'
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Product'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - update
  /v1/sku/{id}/:
    get:
      consumes:
      - application/json
      description: Get product by sku
      parameters:
      - description: sku
        in: path
        name: sku
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - get by sku
swagger: "2.0"
